name: Auto Grade - Sales Table

on:
  push:
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout student submission
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Run automated grader
        run: |
          python tests/test_sales_table.py
